version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./lib:/app/lib
    environment:
      - FLUTTER_WEB_PORT=8080 